services:
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: payment-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 10

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8082:8082"
    environment:
      TZ: Asia/Almaty
      SPRING_RABBITMQ_ADDRESSES: amqp://rabbitmq:5672
      SPRING_RABBITMQ_USERNAME: admin
      SPRING_RABBITMQ_PASSWORD: admin
      SERVER_PORT: 8082
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - default
      - shared-services

networks:
  shared-services:
    external: true
