CREATE TABLE payments (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          order_id BIGINT NOT NULL,
                          status VARCHAR(32) NOT NULL,
                          method VARCHAR(32) NOT NULL,
                          amount DECIMAL(19,2) NOT NULL,
                          currency VARCHAR(3) NOT NULL,
                          created_at TIMESTAMP NOT NULL
);

CREATE TABLE idempotency_keys (
                                  key_value VARCHAR(255) PRIMARY KEY,
                                  status VARCHAR(255),
                                  response CLOB,
                                  status_code INT NOT NULL,
                                  created_at TIMESTAMP
);
